/**
 * Design-as-code · business card target.
 *
 * A second target for the design-as-code compiler, beyond the slide
 * carousel. Cards mirror the existing brand artifact at
 * `cachola_tech/brand/cartao_visita_jardhel.svg` (CT-BRAND-CARD-001) —
 * 85×55 mm ISO 7810 ID-1 with 2 mm bleed, EB Garamond italic for
 * name/title, navy ink + cream background + gold-rule accents,
 * Inter for the wide-tracked uppercase meta line.
 *
 * Designer humano edita o `BusinessCard` em TS, regenera o SVG, ajusta
 * posições no Figma se necessário. A DNA brand (palette, type scale,
 * layer ordering, bleed/trim/safe) está locked in code.
 */

export interface BusinessCard {
  /** Person name, displayed as the largest type. */
  name: string;
  /** Job title — bilingual or single language; rendered below name. */
  title: string;
  /** Wordmark organisation name (e.g., "CACHOLA TECH"). */
  wordmark: string;
  /** Tagline below wordmark (e.g., "The firm, on the record."). */
  tagline: string;
  /** Email line. */
  email: string;
  /** Phone numbers, rendered one per line below email. */
  phones: string[];
  /** Cities meta line (e.g., "SÃO PAULO · EINDHOVEN"). */
  cities: string;
  /** Doc reference shown bottom-left in monospace (e.g., CT-BRAND-CARD-001). */
  ref: string;
  /** Width in millimeters including bleed. Default 89 (= 85 trim + 2 mm bleed each side). */
  widthMm?: number;
  /** Height in millimeters including bleed. Default 59. */
  heightMm?: number;
}

/** Canonical brand palette — locked, do not invent new HEX values. */
export const CARD_PALETTE = {
  navy: '#1F2B3D',
  cream: '#FAF6ED',
  ink: '#121821',
  muted: '#6A7585',
  accent: '#2F4A6B',
  rule: '#B8A97A',
} as const;

const BLEED_MM = 2;

/**
 * Render one BusinessCard to SVG. Output mirrors CT-BRAND-CARD-001:
 * print-ready with bleed/trim/safe guide layers (toggleable, do not
 * print), brand layers ordered for Figma/Illustrator/Affinity.
 */
export function renderBusinessCardSvg(card: BusinessCard): string {
  const W = card.widthMm ?? 89;
  const H = card.heightMm ?? 59;
  const trimX = BLEED_MM;
  const trimY = BLEED_MM;
  const trimW = W - 2 * BLEED_MM;
  const trimH = H - 2 * BLEED_MM;
  const safeX = trimX + 3;
  const safeY = trimY + 3;
  const safeW = trimW - 6;
  const safeH = trimH - 6;

  // Content margins inside trim — tuned to match CT-BRAND-CARD-001 visual.
  const padX = 7;
  const padY = 6.4;

  const phoneLines = card.phones
    .map((phone, i) => {
      const y = (41.0 + i * 4.2).toFixed(1);
      const sz = i === 0 ? 2.5 : 2.5;
      return `    <text x="${padX}" y="${y}" font-size="${sz}">${escapeXml(phone)}</text>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  Cachola Tech · Cartão de visita · ${escapeXml(card.name)}
  Ref: ${escapeXml(card.ref)}
  Formato final: ${trimW.toFixed(0)} × ${trimH.toFixed(0)} mm (ISO 7810 ID-1)
  Bleed ${BLEED_MM} mm cada borda · ${W} × ${H} mm total · Safe zone 3 mm dentro do trim
  Cores em HEX (sRGB). Para CMYK, converter via perfil da gráfica.

  Generated by @batiste-aidk/atrium · design-as-code · business-card target.
  Edite o fixture em TS e regenere via subcomando "compile card" do batiste-fm.
-->
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     width="${W}mm" height="${H}mm"
     viewBox="0 0 ${W} ${H}"
     version="1.1">

  <title>Cachola Tech — Cartão de visita ${escapeXml(card.name)} (${escapeXml(card.ref)})</title>
  <desc>
    Brand palette:
      ctNavy   ${CARD_PALETTE.navy}   structural navy
      ctCream  ${CARD_PALETTE.cream}   background
      ctInk    ${CARD_PALETTE.ink}   body text
      ctMuted  ${CARD_PALETTE.muted}   secondary text
      ctAccent ${CARD_PALETTE.accent}   accent
      ctRule   ${CARD_PALETTE.rule}   gold divider
    Bleed ${BLEED_MM} mm per side. Trim ${trimX},${trimY} → ${trimX + trimW},${trimY + trimH}. Safe zone 3 mm inside trim.
  </desc>

  <defs>
    <style type="text/css"><![CDATA[
      .serif { font-family: "EB Garamond", "Garamond", serif; }
      .sans  { font-family: "Inter", "Helvetica Neue", sans-serif; }
      .italic { font-style: italic; }
      .bold   { font-weight: 700; }
    ]]></style>
  </defs>

  <g id="bleed">
    <rect x="0" y="0" width="${W}" height="${H}"
          fill="none" stroke="#ff0000" stroke-width="0.1"
          stroke-dasharray="0.6,0.3"/>
  </g>

  <g id="trim">
    <rect x="${trimX}" y="${trimY}" width="${trimW}" height="${trimH}"
          fill="none" stroke="#00aa00" stroke-width="0.1"
          stroke-dasharray="0.8,0.4"/>
  </g>

  <g id="safe">
    <rect x="${safeX}" y="${safeY}" width="${safeW}" height="${safeH}"
          fill="none" stroke="#00bcd4" stroke-width="0.08"
          stroke-dasharray="0.4,0.4" opacity="0.5"/>
  </g>

  <g id="background">
    <rect x="${trimX}" y="${trimY}" width="${trimW}" height="${trimH}" fill="${CARD_PALETTE.cream}"/>
  </g>

  <g id="accents" fill="${CARD_PALETTE.rule}">
    <rect x="${padX}" y="${padY}" width="9" height="0.6"/>
    <rect x="${padX}" y="18.6" width="17" height="0.4"/>
  </g>

  <g id="wordmark">
    <text x="${padX}" y="11" class="serif bold italic" font-size="3.6" fill="${CARD_PALETTE.navy}"
          letter-spacing="0.04">${escapeXml(card.wordmark)}</text>
    <text x="${padX}" y="15" class="serif italic" font-size="2.0" fill="${CARD_PALETTE.muted}">${escapeXml(card.tagline)}</text>
  </g>

  <g id="name-title">
    <text x="${padX}" y="24.2" class="serif bold italic" font-size="4.3" fill="${CARD_PALETTE.ink}">${escapeXml(card.name)}</text>
    <text x="${padX}" y="29.4" class="serif italic" font-size="2.7" fill="${CARD_PALETTE.navy}">${escapeXml(card.title)}</text>
  </g>

  <g id="contacts" class="serif" fill="${CARD_PALETTE.ink}">
    <text x="${padX}" y="36.4" font-size="2.7">${escapeXml(card.email)}</text>
${phoneLines}
  </g>

  <g id="meta" class="sans" fill="${CARD_PALETTE.muted}">
    <text x="${(W - BLEED_MM - 5).toFixed(1)}" y="${(H - BLEED_MM - 3.8).toFixed(1)}" font-size="1.9" text-anchor="end" letter-spacing="0.08">${escapeXml(card.cities)}</text>
    <text x="${padX}" y="${(H - BLEED_MM - 2.7).toFixed(1)}" font-size="1.6" style="font-family:monospace">${escapeXml(card.ref)}</text>
  </g>

</svg>
`;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
